language: python

jobs:
  include:
    - stage: validate
      name: "Syntax validation - Python 2.7"
      addons: false
      cache: false
      before_cache: false
      script:
         - python -m compileall -q *

    - name: "Syntax validation - Python 3.7"
      addons: false
      cache: false
      before_cache: false
      dist: xenial
      python: 3.7
      script:
         - python3 -m compileall -q *

    - name: "Flake8 - Python 2.7"
      addons: false
      cache: false
      before_cache: false
      script:
         - .travis/run-flake8
      if: type = pull_request

    - name: "Flake8 - Python 3.7"
      addons: false
      cache: false
      before_cache: false
      dist: xenial
      python: 3.7
      script:
         - .travis/run-flake8
      if: type = pull_request
